[project]
name = "tigerGraph-mcp-server"
version = "1.0.0"
description = "This is a Model Context Protocal Server to itergrate with TigerGraph Version 4.2 Graph Database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.7.0",
    "pytigergraph>=1.8.6",
]
